### ISSUE TITLE
[BUG] - Stab trim not in amber on the ground

### ISSUE THREAD

**Issue by fugotaro** [invernyx/md11-bugs#1062]
### Describe the bug

Stab trim should be in amber on the ground

### Expected behaviour

To have it standard in amber with box around the value when a/c is on the ground
### Evidence

![Schermopname (470)](https://github.com/invernyx/md11-bugs/assets/150957609/60277530-e9fb-4a40-871e-e3bfd4328fda)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Agreement

- [X] Yes

**Comment by TheFightingRaven** [comment]
confirmed in video should be amber and boxed if on ground and not in green band even if there is no green band to display

**Comment by joon44** [comment]
> confirmed in video should be amber and boxed if on ground and not in green band even if there is no green band to display

I believe the behavior is correct now. It is amber and boxed until moved to the green band.

**Comment by turbofandude** [comment]
Resolved in 0.48+

**Comment by fugotaro** [comment]
Not fixed

**Comment by fugotaro** [comment]
To add to this the stab trim green band now shows only after starting two engines like the text says, but from videos like this https://youtu.be/pCiO8qdc1rE?si=nbgud40zDQ7N_6bb&t=212 it seems the green band should show after flaps have been entered on the TO/APPR page and not when atleast two engines have been started

**Comment by TheFightingRaven** [comment]
@turbofandude not resolved, if no green band is present it should also be amber which it isn't

**Comment by turbofandude** [comment]
Resolved (for real) in 0.63+
