### ISSUE TITLE
[BUG] - V2 speed not showing on FMA and incorrect speed bugs displaying 

### ISSUE THREAD

**Issue by fugotaro** [invernyx/md11-bugs#968]
### Describe the bug

V2 speed not showing on FMA and incorrect speed bugs displaying 

### Expected behaviour

To have the V2 speed on the FMA after confirming it on the FMC 
To have a solid speed bug or solid dot next to the V2 speed and having it moving towards V2 speed +10 
To have an open speed bug for the selected speed on the FCP 

### Evidence

https://youtu.be/3wzS6fn8BA8?si=7wHz2HeW-KnbZKWY&t=3030
![Schermopname (433)](https://github.com/invernyx/md11-bugs/assets/150957609/bdcc971b-ddf8-42f6-b676-4d3f3b4cb00b)
![Schermopname (446)](https://github.com/invernyx/md11-bugs/assets/150957609/ccf117cd-62cf-4003-a0f0-64fc937f61ca)

### Simulator

Microsoft Flight Simulator 2020 (MSFS)

### Crash

No

### Agreement

- [X] Yes

**Comment by GenericNerd** [comment]
Can you give steps to reproduce? Did you enter the speeds or were these computed speeds?

**Comment by fugotaro** [comment]
Confirm V speeds from the CDU or enter them yourself. 

It doesn't matter if they're computed or not as both ways you don't get the V2 speed next to the pitch text on the FMA box or the correct bowtie/speed bug on the speed display

**Comment by turbofandude** [comment]
Resolved in 0.42+

**Comment by fugotaro** [comment]
It works great in 0.44! But when you enter the CDU speeds first and then try to overide them manually the pitch speed in the fma go to V2 +10 speed and stays magenta with the magenta dot is still present instead of an filled bowtie for the V2 speed bug. 

Also the L4 key doesn't work on the TO/APPR page with the L5 key entering the V1 speed and L6 key enters Vr and V2 speeds
